<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace GPBMetadata;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad1010a1068656c6c6f776f726c642e70726f746f120a68656c6c6f776f" .
            "726c64221c0a0c48656c6c6f52657175657374120c0a046e616d65180120" .
            "01280922200a0d48656c6c6f526573706f6e7365120f0a076d6573736167" .
            "6518012001280932690a0747726565746572125e0a0853617948656c6c6f" .
            "12182e68656c6c6f776f726c642e48656c6c6f526571756573741a192e68" .
            "656c6c6f776f726c642e48656c6c6f526573706f6e7365221d82d3e49302" .
            "1712152f76312f68656c6c6f776f726c642f7b6e616d657d620670726f74" .
            "6f33"
        ), true);

        static::$is_initialized = true;
    }
}

