// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order/info/info.proto

/*
Package info is a generated protocol buffer package.

It is generated from these files:
	order/info/info.proto

It has these top-level messages:
	AddRequest
	AddResponse
	ListRequest
	ListResponse
*/
package info

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddRequest struct {
	Name       string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Password   string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	VerifyCode string `protobuf:"bytes,3,opt,name=verify_code,json=verifyCode" json:"verify_code,omitempty"`
}

func (m *AddRequest) Reset()                    { *m = AddRequest{} }
func (m *AddRequest) String() string            { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()               {}
func (*AddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AddRequest) GetVerifyCode() string {
	if m != nil {
		return m.VerifyCode
	}
	return ""
}

type AddResponse struct {
	Code    int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Token   string `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
}

func (m *AddResponse) Reset()                    { *m = AddResponse{} }
func (m *AddResponse) String() string            { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()               {}
func (*AddResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AddResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AddResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ListRequest struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ListResponse struct {
	Code    int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ListResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*AddRequest)(nil), "order.info.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "order.info.AddResponse")
	proto.RegisterType((*ListRequest)(nil), "order.info.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "order.info.ListResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Info service

type InfoClient interface {
	// Sends a greeting
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type infoClient struct {
	cc *grpc.ClientConn
}

func NewInfoClient(cc *grpc.ClientConn) InfoClient {
	return &infoClient{cc}
}

func (c *infoClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := grpc.Invoke(ctx, "/order.info.Info/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/order.info.Info/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Info service

type InfoServer interface {
	// Sends a greeting
	Add(context.Context, *AddRequest) (*AddResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
}

func RegisterInfoServer(s *grpc.Server, srv InfoServer) {
	s.RegisterService(&_Info_serviceDesc, srv)
}

func _Info_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.info.Info/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Info_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.info.Info/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Info_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.info.Info",
	HandlerType: (*InfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Info_Add_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Info_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order/info/info.proto",
}

func init() { proto.RegisterFile("order/info/info.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x69, 0x9b, 0x56, 0x9d, 0xfa, 0x8f, 0xc5, 0xd6, 0x10, 0x04, 0x65, 0x4f, 0x9e, 0x12,
	0xd4, 0x83, 0x17, 0x2f, 0xd5, 0x93, 0xa0, 0x87, 0xe6, 0x28, 0x88, 0xac, 0xee, 0x24, 0x2c, 0xb6,
	0x3b, 0x31, 0xbb, 0x56, 0xbc, 0xfa, 0x0a, 0xbe, 0x84, 0xef, 0xe3, 0x2b, 0xf8, 0x20, 0x92, 0xdd,
	0xd8, 0x54, 0x0a, 0x1e, 0xbc, 0x84, 0x99, 0x6f, 0xe6, 0xfb, 0x65, 0x76, 0x06, 0x06, 0x54, 0x4a,
	0x2c, 0x13, 0xa5, 0x33, 0x72, 0x9f, 0xb8, 0x28, 0xc9, 0x12, 0x03, 0x27, 0xc7, 0x95, 0x12, 0xed,
	0xe5, 0x44, 0xf9, 0x04, 0x13, 0x51, 0xa8, 0x44, 0x68, 0x4d, 0x56, 0x58, 0x45, 0xda, 0xf8, 0x4e,
	0x7e, 0x0b, 0x30, 0x92, 0x32, 0xc5, 0xa7, 0x67, 0x34, 0x96, 0x31, 0x08, 0xb4, 0x98, 0x62, 0xd8,
	0x3a, 0x68, 0x1d, 0xae, 0xa5, 0x2e, 0x66, 0x11, 0xac, 0x16, 0xc2, 0x98, 0x17, 0x2a, 0x65, 0xd8,
	0x76, 0xfa, 0x3c, 0x67, 0xfb, 0xd0, 0x9f, 0x61, 0xa9, 0xb2, 0xd7, 0xbb, 0x07, 0x92, 0x18, 0x76,
	0x5c, 0x19, 0xbc, 0x74, 0x41, 0x12, 0xf9, 0x18, 0xfa, 0x0e, 0x6f, 0x0a, 0xd2, 0x06, 0x2b, 0xbe,
	0x6b, 0xac, 0xf8, 0xdd, 0xd4, 0xc5, 0x2c, 0x84, 0x95, 0x29, 0x1a, 0x23, 0x72, 0xac, 0xf1, 0x3f,
	0x29, 0xdb, 0x81, 0xae, 0xa5, 0x47, 0xd4, 0x35, 0xd7, 0x27, 0xfc, 0x14, 0xfa, 0x57, 0xca, 0xd8,
	0xbf, 0x46, 0x9e, 0x1b, 0xdb, 0x8b, 0xc6, 0x33, 0x58, 0xf7, 0xc6, 0xff, 0x0c, 0x73, 0xfc, 0xd1,
	0x82, 0xe0, 0x52, 0x67, 0xc4, 0xae, 0xa1, 0x33, 0x92, 0x92, 0x0d, 0xe3, 0x66, 0xc7, 0x71, 0xb3,
	0xc2, 0x68, 0x77, 0x49, 0xf7, 0xbf, 0xe3, 0x83, 0xb7, 0xcf, 0xaf, 0xf7, 0xf6, 0x16, 0xdf, 0x48,
	0x66, 0x47, 0x89, 0x3f, 0x9b, 0x90, 0x92, 0x8d, 0x21, 0xa8, 0xa6, 0x62, 0xbf, 0x7c, 0x0b, 0x0f,
	0x8c, 0xc2, 0xe5, 0x42, 0x4d, 0x1c, 0x3a, 0xe2, 0x36, 0xdf, 0x6c, 0x88, 0x13, 0x65, 0xec, 0x79,
	0xef, 0x26, 0xa8, 0x9a, 0xef, 0x7b, 0xee, 0xc4, 0x27, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe7,
	0x51, 0x21, 0xd6, 0x25, 0x02, 0x00, 0x00,
}
