<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order/info/info.proto

namespace GPBMetadata\Order\Info;

class Info
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab9030a156f726465722f696e666f2f696e666f2e70726f746f120a6f72" .
            "6465722e696e666f22410a0a41646452657175657374120c0a046e616d65" .
            "18012001280912100a0870617373776f726418022001280912130a0b7665" .
            "726966795f636f6465180320012809223b0a0b416464526573706f6e7365" .
            "120c0a04636f6465180120012805120f0a076d6573736167651802200128" .
            "09120d0a05746f6b656e180320012809222a0a0b4c697374526571756573" .
            "74120c0a046e616d65180120012809120d0a05746f6b656e180220012809" .
            "222d0a0c4c697374526573706f6e7365120c0a04636f6465180120012805" .
            "120f0a076d65737361676518022001280932a8010a04496e666f124d0a03" .
            "41646412162e6f726465722e696e666f2e416464526571756573741a172e" .
            "6f726465722e696e666f2e416464526573706f6e7365221582d3e493020f" .
            "220d2f76312f6f726465722f61646412510a044c69737412172e6f726465" .
            "722e696e666f2e4c697374526571756573741a182e6f726465722e696e66" .
            "6f2e4c697374526573706f6e7365221682d3e4930210220e2f76312f6f72" .
            "6465722f6c69737442065a04696e666f620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

