<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order/info/info.proto

namespace GPBMetadata\Order\Info;

class Info
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a98030a156f726465722f696e666f2f696e666f2e70726f746f12056f72" .
            "64657222410a0a41646452657175657374120c0a046e616d651801200128" .
            "0912100a0870617373776f726418022001280912130a0b7665726966795f" .
            "636f6465180320012809223b0a0b416464526573706f6e7365120c0a0463" .
            "6f6465180120012805120f0a076d657373616765180220012809120d0a05" .
            "746f6b656e180320012809222a0a0b4c69737452657175657374120c0a04" .
            "6e616d65180120012809120d0a05746f6b656e180220012809222d0a0c4c" .
            "697374526573706f6e7365120c0a04636f6465180120012805120f0a076d" .
            "6573736167651802200128093294010a04496e666f12430a034164641211" .
            "2e6f726465722e416464526571756573741a122e6f726465722e41646452" .
            "6573706f6e7365221582d3e493020f220d2f76312f6f726465722f616464" .
            "12470a044c69737412122e6f726465722e4c697374526571756573741a13" .
            "2e6f726465722e4c697374526573706f6e7365221682d3e4930210220e2f" .
            "76312f6f726465722f6c697374620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

