<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/type.proto

namespace GPBMetadata\Common;

class Type
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a780a11636f6d6d6f6e2f747970652e70726f746f1206636f6d6d6f6e22" .
            "250a08526573706f6e7365120c0a04636f6465180120012805120b0a036d" .
            "736718022001280922220a054572726f72120c0a04636f64651801200128" .
            "05120b0a036d736718022001280942085a06636f6d6d6f6e620670726f74" .
            "6f33"
        ), true);

        static::$is_initialized = true;
    }
}

