// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/info/info.proto

/*
Package User_Info is a generated protocol buffer package.

It is generated from these files:
	user/info/info.proto

It has these top-level messages:
	LoginRequest
	UserInfo
	LoginResponse
	LogoutRequest
	LogoutResponse
*/
package User_Info

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "common"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	Error      *common.Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Name       string        `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Password   string        `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	VerifyCode string        `protobuf:"bytes,4,opt,name=verify_code,json=verifyCode" json:"verify_code,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginRequest) GetError() *common.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *LoginRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetVerifyCode() string {
	if m != nil {
		return m.VerifyCode
	}
	return ""
}

type UserInfo struct {
	Uid  int64  `protobuf:"varint,1,opt,name=Uid" json:"Uid,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginResponse struct {
	Error *common.Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Info  *UserInfo     `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginResponse) GetError() *common.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *LoginResponse) GetInfo() *UserInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type LogoutRequest struct {
	Error *common.Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Name  string        `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Token string        `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
}

func (m *LogoutRequest) Reset()                    { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string            { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()               {}
func (*LogoutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LogoutRequest) GetError() *common.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *LogoutRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LogoutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutResponse struct {
	Error *common.Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *LogoutResponse) Reset()                    { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string            { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()               {}
func (*LogoutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LogoutResponse) GetError() *common.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "User.Info.LoginRequest")
	proto.RegisterType((*UserInfo)(nil), "User.Info.UserInfo")
	proto.RegisterType((*LoginResponse)(nil), "User.Info.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "User.Info.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "User.Info.LogoutResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Info service

type InfoClient interface {
	// Sends a greeting
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
}

type infoClient struct {
	cc *grpc.ClientConn
}

func NewInfoClient(cc *grpc.ClientConn) InfoClient {
	return &infoClient{cc}
}

func (c *infoClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/User.Info.Info/login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := grpc.Invoke(ctx, "/User.Info.Info/logout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Info service

type InfoServer interface {
	// Sends a greeting
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
}

func RegisterInfoServer(s *grpc.Server, srv InfoServer) {
	s.RegisterService(&_Info_serviceDesc, srv)
}

func _Info_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User.Info.Info/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Info_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User.Info.Info/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Info_serviceDesc = grpc.ServiceDesc{
	ServiceName: "User.Info.Info",
	HandlerType: (*InfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "login",
			Handler:    _Info_Login_Handler,
		},
		{
			MethodName: "logout",
			Handler:    _Info_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/info/info.proto",
}

func init() { proto.RegisterFile("user/info/info.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0x4e, 0xa1, 0x10, 0x18, 0xc4, 0xc0, 0x8a, 0x5a, 0x2b, 0x89, 0x64, 0x3d, 0x48, 0x38, 0xb4,
	0x06, 0xe3, 0x85, 0xab, 0xf1, 0x60, 0x62, 0x3c, 0x34, 0x21, 0x1e, 0x8c, 0x9a, 0x4a, 0x17, 0xd2,
	0x08, 0x3b, 0x75, 0x77, 0xab, 0xe1, 0x6a, 0x7c, 0x03, 0x5f, 0xc7, 0xb7, 0xf0, 0x15, 0x7c, 0x10,
	0xb3, 0x5b, 0x40, 0xfc, 0x39, 0x68, 0xbc, 0x34, 0x33, 0xf3, 0x4d, 0xbe, 0x6f, 0xbe, 0xaf, 0x0b,
	0x8d, 0x54, 0x32, 0xe1, 0xc7, 0x7c, 0x88, 0xe6, 0xe3, 0x25, 0x02, 0x15, 0x92, 0x72, 0x5f, 0x32,
	0xe1, 0x9d, 0xf0, 0x21, 0xba, 0xf5, 0x01, 0x4e, 0x26, 0xc8, 0x7d, 0x35, 0x4d, 0x58, 0x86, 0xba,
	0xcd, 0x11, 0xe2, 0x68, 0xcc, 0xfc, 0x30, 0x89, 0xfd, 0x90, 0x73, 0x54, 0xa1, 0x8a, 0x91, 0xcb,
	0x0c, 0xa5, 0x4f, 0x16, 0xac, 0x9c, 0xe2, 0x28, 0xe6, 0x01, 0xbb, 0x4b, 0x99, 0x54, 0x64, 0x17,
	0x0a, 0x4c, 0x08, 0x14, 0x8e, 0xd5, 0xb2, 0xda, 0x95, 0x6e, 0xd5, 0xcb, 0x18, 0xbd, 0x63, 0x3d,
	0x0c, 0x32, 0x8c, 0x10, 0xb0, 0x79, 0x38, 0x61, 0x4e, 0xae, 0x65, 0xb5, 0xcb, 0x81, 0xa9, 0x89,
	0x0b, 0xa5, 0x24, 0x94, 0xf2, 0x01, 0x45, 0xe4, 0xe4, 0xcd, 0x7c, 0xd1, 0x93, 0x1d, 0xa8, 0xdc,
	0x33, 0x11, 0x0f, 0xa7, 0xd7, 0x03, 0x8c, 0x98, 0x63, 0x1b, 0x18, 0xb2, 0xd1, 0x11, 0x46, 0x8c,
	0xee, 0x43, 0x49, 0x9b, 0xd0, 0x1e, 0x48, 0x0d, 0xf2, 0xfd, 0x38, 0x32, 0xfa, 0xf9, 0x40, 0x97,
	0x5a, 0xee, 0x6c, 0x49, 0x4e, 0xd7, 0xf4, 0x12, 0xaa, 0xb3, 0xbb, 0x65, 0x82, 0x5c, 0xb2, 0xdf,
	0x1d, 0xbe, 0x07, 0xb6, 0x0e, 0xce, 0x30, 0x55, 0xba, 0x6b, 0xde, 0x22, 0x39, 0x6f, 0x2e, 0x1f,
	0x98, 0x05, 0x7a, 0x65, 0xe8, 0x31, 0x55, 0xff, 0xce, 0xa5, 0x01, 0x05, 0x85, 0xb7, 0x8c, 0xcf,
	0x42, 0xc9, 0x1a, 0x7a, 0x08, 0xab, 0x73, 0xfe, 0x3f, 0xdc, 0xdf, 0x7d, 0xb1, 0xc0, 0x36, 0x21,
	0x9d, 0x43, 0x61, 0xac, 0xed, 0x93, 0xcd, 0x25, 0x0f, 0xcb, 0x3f, 0xd2, 0x75, 0xbe, 0x03, 0x99,
	0x12, 0xdd, 0x7e, 0x7c, 0x7d, 0x7b, 0xce, 0xad, 0xd3, 0x9a, 0xaf, 0x37, 0x7c, 0xbd, 0xe1, 0x9b,
	0x8d, 0x9e, 0xd5, 0x21, 0x17, 0x50, 0x1c, 0x9b, 0xc3, 0xc8, 0x17, 0x82, 0x8f, 0x2c, 0xdc, 0xad,
	0x1f, 0x90, 0x19, 0x77, 0xd3, 0x70, 0x6f, 0xd0, 0xfa, 0x67, 0x6e, 0x4c, 0x55, 0xcf, 0xea, 0xdc,
	0x14, 0xcd, 0xa3, 0x3b, 0x78, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x30, 0x97, 0x8d, 0xb7, 0xc8, 0x02,
	0x00, 0x00,
}
