<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/info/info.proto

namespace GPBMetadata\User\Info;

class Info
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Type::initOnce();
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a98040a14757365722f696e666f2f696e666f2e70726f746f1209757365" .
            "722e696e666f1a1c676f6f676c652f6170692f616e6e6f746174696f6e73" .
            "2e70726f746f22610a0c4c6f67696e52657175657374121c0a056572726f" .
            "7218012001280b320d2e636f6d6d6f6e2e4572726f72120c0a046e616d65" .
            "18022001280912100a0870617373776f726418032001280912130a0b7665" .
            "726966795f636f6465180420012809222d0a0d4c6f67696e526573706f6e" .
            "7365121c0a056572726f7218012001280b320d2e636f6d6d6f6e2e457272" .
            "6f72224a0a0d4c6f676f757452657175657374121c0a056572726f721801" .
            "2001280b320d2e636f6d6d6f6e2e4572726f72120c0a046e616d65180220" .
            "012809120d0a05746f6b656e180320012809222e0a0e4c6f676f75745265" .
            "73706f6e7365121c0a056572726f7218012001280b320d2e636f6d6d6f6e" .
            "2e4572726f7232b8010a04496e666f12550a056c6f67696e12172e757365" .
            "722e696e666f2e4c6f67696e526571756573741a182e757365722e696e66" .
            "6f2e4c6f67696e526573706f6e7365221982d3e4930213220e2f76312f75" .
            "7365722f6c6f67696e3a012a12590a066c6f676f757412182e757365722e" .
            "696e666f2e4c6f676f7574526571756573741a192e757365722e696e666f" .
            "2e4c6f676f7574526573706f6e7365221a82d3e4930214220f2f76312f75" .
            "7365722f6c6f676f75743a012a42065a04696e666f620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

